#!/bin/sh
echo
shuf -n 1 quotes.csv
echo
if [ $1 = "dev" ] || [ -z $1 ]; then
if [ !-z ]; then shift; fi

echo "Alfred! running dev $1"
docker-compose -f docker-compose.yml -f dev.yml up $1

elif [ $1 = "prod" -o $1 = "production" ]; then
shift
echo "Alfred! running production $1"
docker-compose down && \
docker-compose -f docker-compose.yml -f production.yml up --build -d $1

elif [ $1 = "i" -o $1 = "install" ]; then
  shift
  echo "installing dependencies"
  docker-compose run dev yarn install

elif [ $1 = "demo" -o $1 = "download" -o $1 = "samples" ]; then
  shift
  echo "downloading demo media"
  mkdir -p videos && cd videos
  wget -nc https://storage.googleapis.com/tower-bucket/moon.mp4
  wget -nc http://https://storage.googleapis.com/tower-bucket/train.mp4
  wget -nc https://storage.googleapis.com/tower-bucket/ATripToTheMoon-300k.mp4
  wget -nc https://storage.googleapis.com/tower-bucket/TheGreatTrainRobbery-300k.mp4
  cd ..
fi
