version: '3.3'

services:
  # TODO Development Reloader description
  # dev:
  #   ports:
  #     - "1234:1234"
  #     - "1235:1235"
  #   networks:
  #     - alfred_isolated
  #   command: parcel watch /app/src/* --hmr-port 1235
  website:
    ports:
      - "8000:1234"
      - "1235:1235"
    networks:
      - alfred_isolated
    command: npm run dev
# TODO API description
  api:
    ports:
      - "1234:80"
    networks:
      - alfred_isolated
networks:
  alfred_isolated:
