version: '3.3'

services:
  # TODO Development Reloader description
  website:
    ports:
      - 1234:1234
    command: npm run dev

# TODO API description
  api:
    ports:
      - 8000:80

  renderer:
    build: ./api/
    command: celery -A tasks worker --loglevel=info
    networks:
      - alfred_isolated
    volumes:
      - ./api/:/app/
      - ./videos/:/app/videos/
      - ./cred.json:/cred.json
    depends_on:
      - rabbit
    environment:
      - CELERY_BROKER=pyamqp://guest@rabbit//
      - CELERY_BACKEND=rpc://
      - DB_URL=mongodb://db:27017
      - GOOGLE_APPLICATION_CREDENTIALS=/cred.json
  flower:
    build: ./flower/
    networks:
      - alfred_isolated
    ports:
      - 5555:5555
    command: flower --port=5555 --broker=pyamqp://guest@rabbit//
