version: '3.8'

services:
  # TODO Development Reloader description
  website:
    ports:
      - 8001:8001
    command: yarn run dev

# TODO API description
  api:
    ports:
      - 8000:80

  renderer:
    build: ./api/
    image: alfred_worker
    command: celery -A tasks:renderer --workdir /app/ -b mongodb://db:27017/celery --result-backend mongodb://db:27017/celery worker --loglevel=info
    networks:
      - alfred_isolated
    volumes:
      - ./api/:/app/
      - ./videos/:/app/videos/
      - ./cred.json:/cred.json
    depends_on:
      - 'db'
    environment:
      - CELERY_BROKER=mongodb://db:27017/celery
      - CELERY_BACKEND=mongodb
      - DB_URL=mongodb://db:27017
      - GOOGLE_APPLICATION_CREDENTIALS=/cred.json
  db:
    ports:
      - 27017:27017