version: '3.3'

services:
  # TODO Development Reloader description
  dev:
    labels:
      - alfred
    ports:
      - "1234:1234"
      - "1235:1235"
    command: parcel watch /app/src/* --hmr-port 1235
# TODO API description
  api:
    labels:
      - alfred
    ports:
      - "8000:80"
