version: '3.3'

services:
  # TODO Development Reloader description
  website:
    ports:
      - "1234:1234"
    networks:
      - alfred_isolated
    command: npm run dev
# TODO API description
  api:
    ports:
      - "8000:80"
    networks:
      - alfred_isolated
networks:
  alfred_isolated:
