version: '3.3'

services:
  # TODO Development Reloader description
  website:
    build: ./website/
    image: alfred_site
    volumes:
      - "./website/:/app/"
  # TODO API description
  api:
    build: ./api/
    image: alfred_api
    depends_on:
      - website
      - db
    volumes:
      - "./api/:/app/"
      - "./website/dist/:/app/dist/"
      - "./videos/:/app/videos/"
  db:
    image: mvertes/alpine-mongo
    volumes:
      - './api/database:/data/db'
