version: '3.3'

services:
  # TODO Development Reloader description
  dev:
    build: ./builder/
    image: parceldock
    volumes:
      - .:/app/
      - ./dist/:/app/dist/
  # TODO API description
  api:
    build: ./api/
    image: alfred_api
    volumes:
      - './api/api.py:/app/main.py'
      - './api/partial.py:/app/partial.py'
      - './dist/:/app/dist/'
      - './videos/:/app/videos/'
      - './api/db.py:/app/db.py'
