version: '3.3'

services:
  # TODO Development Reloader description
  dev:
    build: ./builder/
    image: parceldock
    labels:
      - alfred
    volumes:
      - "./:/app/"
      - "./dist/:/app/dist/"
  # TODO API description
  api:
    build: ./api/
    image: alfred_api
    labels:
      - alfred
    volumes:
      - "./api/:/app/"
      - "./dist/:/app/dist/"
      - "./videos/:/app/videos/"
