version: '3.3'

services:
  # # TODO Development Reloader description
  # dev:
  #   build: ./builder/
  #   image: parceldock
  #   volumes:
  #     - "./:/app/"
  #     - "./dist/:/app/dist/"
  website:
    build: ./website/
    image: alfred_site
    volumes:
      - "./website/:/app/"
  # TODO API description
  api:
    build: ./api/
    image: alfred_api
    volumes:
      - "./api/:/app/"
      - "./dist/:/app/dist/"
      - "./videos/:/app/videos/"
