version: '3.8'
networks:
  alfred_isolated:
  alfred_outgoing:
    driver: bridge
services:
  # TODO Development Reloader description
  website:
    build: ./website/
    image: alfred_site
    volumes:
      - ./website/:/app/

  # TODO API description
  api:
    build: ./api/
    image: alfred_api
    depends_on:
      - website
      - db
    volumes:
      - ./api/:/app/
      - ./website/dist/:/app/dist/
      - ./videos/:/app/videos/
      - ./cred_api.json:/cred.json
    networks:
      - alfred_isolated
      - alfred_outgoing
    environment:
      - CELERY_BROKER=mongodb://db:27017/celery
      - CELERY_BACKEND=mongodb://db:27017/celery
      - DB_URL=mongodb://db:27017
      - GOOGLE_APPLICATION_CREDENTIALS=/cred.json
    env_file:
      - .email
      - .secret_key

  db:
    image: mongo:bionic
    volumes:
      - ./database:/data/db
    networks:
      - alfred_isolated

  flower:
    build: ./flower/
    networks:
      - alfred_isolated
    ports:
      - 5555:5555
    command: celery flower --port=5555 --broker=mongodb://db:27017/celery
