version: '3.3'

services:
  dev:
    build: ./builder/
    image: parceldock
    ports:
      - "1234:1234"
      - "1235:1235"
    volumes:
      - .:/app/
      - ./dist/:/app/dist/
  api:
    build: ./api/
    image: alfred_api
    volumes:
      - './api/api.py:/app/main.py'
      - './dist/:/app/dist/'
