version: '3.3'

services:
  dev:
    build: ./builder/
    image: parceldock
    volumes:
      - .:/app/
      - ./dist/:/app/dist/
  api:
    build: ./api/
    image: alfred_api
    volumes:
      - './api/api.py:/app/main.py'
      - './dist/:/app/dist/'
      - './videos/:/app/videos/'
