site_name: Alfred
side_description: automatic video editing
site_url: https://docs.alfred.quaternion.media
# repo_url: https://github.com/quaternionmedia/alfred

nav:
  - Home: index.md
  - About: about.md
  - Models: models.md
  - Example: example.md
  - API: api.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

theme:
  name: material
  logo: assets/al-white.png
  favicon: assets/al-white.png
  icon: assets/al-white.svg
  palette:
    - media: "(prefers-color-scheme: dark)" # 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" # 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/quaternionmedia/alfred
    # - icon: fontawesome/brands/website
    #   link: https://alfred.quaternion.media
