version: '3.8'

networks:
  web:
    external:
      name: web

services:
  api:
    networks:
      - web
    volumes:
      - ./alfred/otto/fonts:/usr/share/fonts/truetype/
    labels:
      - traefik.http.services.alfred.loadbalancer.server.port=80
      - traefik.http.routers.alfred.rule=Host(`alfred.quaternion.media`)
      - traefik.http.routers.alfred.tls=true
      - traefik.http.routers.alfred.tls.certresolver=le
      - traefik.http.routers.alfred.entrypoints=websecure
      - traefik.docker.network=web
    environment:
      - ALFRED_PRODUCTION=true
  db:
    ports:
      - 192.168.192.52:27017:27017
