version: '3.3'

networks:
  db:
  web:
    external:
      name: web

services:
  api:
    networks:
      - web
      - db
    labels:
      - traefik.http.routers.alfred.rule=Host(`alfred.quaternion.media`)
      - traefik.http.routers.alfred.tls=true
      - traefik.http.routers.alfred.tls.certresolver=le
      - traefik.http.routers.alfred.entrypoints=websecure
  db:
    networks:
      - db
