version: '3.8'

services:
  cy:
    image: cypress/included:9.7.0
    depends_on:
      - api
      - db
    volumes:
      - ./website/:/e2e/
    working_dir: /e2e/
    networks:
      - alfred_isolated
    environment:
      CYPRESS_baseUrl: http://api/
      CYPRESS_RECORD_KEY: ${CYPRESS_RECORD_KEY}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    command: cypress run --record
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: alfred_api
    depends_on:
      - website
      - db
    volumes:
      - ./alfred/:/app/:Z
      - ./website/dist/:/app/dist/:z
      - ./videos/:/app/videos/:Z
      - ./cred_api.json:/cred.json:Z
    networks:
      - alfred_isolated
      - alfred_outgoing
    environment:
      - CELERY_BROKER=mongodb://db:27017/celery
      - CELERY_BACKEND=mongodb://db:27017/celery
      - DB_URL=mongodb://db:27017
      - DB_NAME=alfred
      - GOOGLE_APPLICATION_CREDENTIALS=/cred.json

  db:
    image: mongo:bionic
    volumes:
      - ./database:/data/db
    networks:
      - alfred_isolated
