version: '3.8'

services:
  cy:
    image: cypress/included:9.1.1
    depends_on:
      - website
      - api
      - db
    volumes:
      - ./website/:/e2e/
    working_dir: /e2e/
    networks:
      - alfred_isolated
    environment:
      CYPRESS_baseUrl: http://api/
      CYPRESS_RECORD_KEY: ${CYPRESS_RECORD_KEY}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    command: cypress run --record

  website:
    command: yarn parcel watch /app/src/index.html /app/src/*.svg /app/src/*.png

  renderer:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: alfred_worker
    command: celery -A alfred.core.utils.tasks:renderer --workdir /app/ -b mongodb://db:27017/celery --result-backend mongodb://db:27017/celery worker --loglevel=info
    networks:
      - alfred_isolated
    volumes:
      - ./alfred/:/app/
      - ./alfred/otto:/otto/
      - ./videos/:/app/videos/
      - ./cred.json:/cred.json
    depends_on:
      - 'db'
    environment:
      - CELERY_BROKER=mongodb://db:27017/celery
      - CELERY_BACKEND=mongodb
      - DB_URL=mongodb://db:27017
      - DB_NAME=alfred
      - GOOGLE_APPLICATION_CREDENTIALS=/cred.json