version: '3.8'

services:
  cy:
    image: cypress/included:9.7.0
    depends_on:
      - api
      - db
    volumes:
      - ./website/:/e2e/
    working_dir: /e2e/
    networks:
      - alfred_isolated
    environment:
      CYPRESS_baseUrl: http://api/
      CYPRESS_RECORD_KEY: ${CYPRESS_RECORD_KEY}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    command: cypress run --record
