FROM node:alpine

RUN apk add util-linux make
WORKDIR /app
RUN npm upgrade -g yarn
CMD ["$(npm bin)/parcel", "build", "/app/src/index.html", "/app/src/*.csv", "/app/src/*.svg", "--target", "browser"]
